# Generated by Django 5.2 on 2025-04-25 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('quantidade', models.PositiveIntegerField()),
                ('tamanho', models.CharField(max_length=10)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='data_admissao',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='email',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='telefone',
        ),
        migrations.AddField(
            model_name='colaborador',
            name='matricula',
            field=models.CharField(default='DEFAULT_VALUE', max_length=50),
        ),
    ]
